-- MySQL Script generated by MySQL Workbench
-- Mon 04 Dec 2023 04:47:46 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dbsquad-hub
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbsquad-hub
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbsquad-hub` ;
USE `dbsquad-hub` ;

-- -----------------------------------------------------
-- Table `dbsquad-hub`.`funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsquad-hub`.`funcionarios` (
  `cpf` CHAR(11) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `nome` VARCHAR(45) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `cargo` VARCHAR(45) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  PRIMARY KEY (`cpf`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsquad-hub`.`projetos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsquad-hub`.`projetos` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `descricao` VARCHAR(120) COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  `data_inicio` DATE NOT NULL,
  `data_termino` DATE NOT NULL,
  `atividade` CHAR(1) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsquad-hub`.`squads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsquad-hub`.`squads` (
  `id` INT NOT NULL,
  `projeto_id` INT NOT NULL,
  `frontend_cpf` CHAR(11) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `backend_cpf` CHAR(11) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `po_cpf` CHAR(11) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_squads_projeto_id_idx` (`projeto_id` ASC) VISIBLE,
  INDEX `fk_squads_frontend_cpf` (`frontend_cpf` ASC) VISIBLE,
  INDEX `fk_squads_backend_cpf` (`backend_cpf` ASC) VISIBLE,
  INDEX `fk_squads_po_cpf` (`po_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_squads_backend_cpf`
    FOREIGN KEY (`backend_cpf`)
    REFERENCES `dbsquad-hub`.`funcionarios` (`cpf`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_squads_frontend_cpf`
    FOREIGN KEY (`frontend_cpf`)
    REFERENCES `dbsquad-hub`.`funcionarios` (`cpf`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_squads_po_cpf`
    FOREIGN KEY (`po_cpf`)
    REFERENCES `dbsquad-hub`.`funcionarios` (`cpf`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_squads_projeto_id`
    FOREIGN KEY (`projeto_id`)
    REFERENCES `dbsquad-hub`.`projetos` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsquad-hub`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsquad-hub`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `senha` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `papel` VARCHAR(20) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
